Importing Tensorflow library

In [ ]:
import tensorflow as tf

Downloading and preparing MNIST datasets for traning and testing purpose, converting samples from integer to floating

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Build the tf.keras.Sequential model by stacking layers by Choosing an optimizer and loss function for training:

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

Each example has a vector of "Logits" and "Log-Odds" collected as prediction parameters.
Logits: The vector of raw (non-normalized) predictions that a classification Log-Odds: model generates and The logarithm of the odds of some event.

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.09043998, -0.2651177 ,  0.07668626,  0.3347767 , -0.07573164,
         0.09855483,  0.03392034,  0.6592796 ,  0.43973333,  0.53333807]],
      dtype=float32)

Converting extracted logits to "probabilities" for each class using softmax function

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.07359204, 0.06179727, 0.0869787 , 0.11259008, 0.07468246,
        0.08890174, 0.08333738, 0.15575068, 0.12504958, 0.13732015]],
      dtype=float32)

The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.4202235

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=7)

Epoch 1/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0392 - accuracy: 0.9870
Epoch 2/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0374 - accuracy: 0.9877
Epoch 3/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0336 - accuracy: 0.9885
Epoch 4/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0343 - accuracy: 0.9883
Epoch 5/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0314 - accuracy: 0.9895
Epoch 6/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0300 - accuracy: 0.9898
Epoch 7/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0303 - accuracy: 0.9894


In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.97481961e-11, 3.30624798e-11, 3.59594923e-11, 5.99729174e-06,
        2.40971900e-16, 6.74440376e-13, 1.17813262e-15, 9.99994040e-01,
        1.25122239e-11, 2.26204744e-08],
       [7.61465017e-17, 3.29670402e-10, 1.00000000e+00, 5.81370674e-10,
        9.03804798e-29, 9.77312544e-15, 1.32542101e-16, 6.12095685e-29,
        1.52478297e-15, 4.37021780e-20],
       [1.28945701e-10, 9.99955654e-01, 2.80267951e-08, 5.91710569e-10,
        1.93546327e-07, 8.27435731e-10, 3.87521141e-06, 2.37041168e-05,
        1.66083773e-05, 8.52478177e-09],
       [9.99999642e-01, 2.69449280e-16, 3.60154822e-08, 8.73870906e-11,
        1.71978248e-11, 1.16190835e-08, 2.91213837e-07, 5.19358945e-10,
        9.63875054e-17, 1.02552535e-08],
       [3.32742234e-09, 5.70601553e-18, 2.82389268e-09, 4.01729810e-13,
        9.99041736e-01, 2.38773628e-13, 1.38322740e-08, 8.89343312e-07,
        1.10118123e-10, 9.57415323e-04]], dtype=float32)>